blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import blogDetail, byCategory, add_comment, index

app_name = 'blog'
urlpatterns = [
    path('<date>/<slug>/', blogDetail, name='blog-detail'),
    path('category/<title>/', byCategory, name='by-category'),
    path('add-comment/<blog_id>',
         add_comment, name='add-comment'),
    path('', index, name='home'),
]

discography/urls.py
from django.contrib import admin
from django.urls import path, include

from discography.views import filter_products, remove_from_wish, remove_from_cart, discoMasonary, discoAll, songDetail, index, add_toFav, productDetail, shop, searched, add_to_cart, products_by_category, add_review_url, update_downloads, update_streams


app_name = 'discography'
urlpatterns = [
    path('shop/', shop, name='shop'),
    path('p/<pk>/<slug>', productDetail, name='product-detail'),
    path('album/<pk>/<slug>', songDetail, name='album-detail'),
    path('album/p/search/', searched, name='search'),
    path('album/p/add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('album/p/remove-from-cart/<slug>/',
         remove_from_cart, name='remove-from-cart'),
    path('album/p/add-review/<product_id>',
         add_review_url, name='add-review'),
    path('album/products-by-category/<category>/',
         products_by_category, name='products-by-category'),
    path('track/update-streams/<pk>/', update_streams, name='update-streams'),
    path('track/update-downloads/<pk>/',
         update_downloads, name='update-downloads'),
    path('track/favourite/<album_pk>/<song_pk>/',
         add_toFav, name='add-to-fav'),
    path('', index, name='home'),
    path('p/filter/', filter_products, name='product-filter'),
    path('masonry/', discoMasonary, name='masonry'),
    path('all', discoAll, name='all'),
    path('remove-from-wish/<type>/<pk>/',
         remove_from_wish, name='remove-from-wish'),

]

events/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import eventByCategory, eventDetail, events, eventsAll

app_name = 'events'
urlpatterns = [

    path('category/<category>', eventByCategory, name='category'),
    path('detail/<pk>', eventDetail, name='detail'),
    path('', events, name='events-masonry'),
    path('all/', eventsAll, name='events-all'),
]

kaneweb/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('discography/', include('discography.urls', namespace='discography')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('artist-media/', include('media.urls', namespace='media')),
    path('events/', include('events.urls', namespace='events')), ]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

media/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import videoByCategory, videoDetail, galleryDetail, galleryByCategory, galleryMasonary, galleryStapel, videoMasonary
app_name = 'media'
urlpatterns = [

    path('video/category/<category>', videoByCategory, name='video-category'),
    path('video/detail/<pk>', videoDetail, name='video-detail'),
    path('gallery/category/<category>',
         galleryByCategory, name='gallery-category'),
    path('gallery/detail/<pk>', galleryDetail, name='gallery-detail'),
    path('video/masonary/', videoMasonary, name='video-masonry'),
    path('', galleryMasonary, name='gallery-masonry'),
    path('gallery/stapel/', galleryStapel, name='gallery-stapel'),
]

shop/urls.py
from django.urls import path, re_path
from .views import order, order_detail, payment_status, payment,  cart, checkout, wishlist

app_name = 'shop'

urlpatterns = [
    path('order/', order, name='order'),
    path('order-detail/<code>/', order_detail, name='order-detail'),
    path('order/<order_code>/',
         payment_status, name='payment-status'),
    path('cart/', cart, name='cart'),
    path('wishlist/', wishlist, name='wishlist'),
    path('checkout/', checkout, name='checkout'),
    path('payment/<type>/<order_id>/', payment, name='payment'),
]

templates/layouts/footer.html
{% load static %}

<footer id="footer">

    <div class="container">
        <div class="row">

            <div class="col-sm-4">

                <aside id="text-2" class="widget_text widget group">
                    <h3 class="widget-title">Holykane</h3>
                    <div class="textwidget">
                        <p>

                            Holykane is an independent solo artist, who seek to impact the world with his unique songs and aura.
                            He began in the year 2014 as a young producer and evolved into a vocal artist, same time finding his place in the entertainment industry.


                        </p>
                    </div>
                </aside>
                <aside id="socials-ignited-2" class="widget_socials_ignited widget group">
                    <h3 class="widget-title">Socials</h3>
                    <div class="ci-socials-ignited ci-socials-ignited-fa">
                        <a href="#" target="_blank" class="disabled" rel="nofollow"><i class="fa fa-facebook"></i></a>
                        <a href="https://www.instagram.com/holy_kane/" target="_blank" rel="nofollow"><i class="fa fa-instagram"></i></a>
                        <a href="https://twitter.com/oh_holykane" target="_blank" rel="nofollow"><i class="fa fa-twitter"></i></a>
                        <a href="https://www.youtube.com/channel/UCqaX45IOEo89P1EMhr0g8oA" target="_blank" rel="nofollow"><i class="fa fa-youtube"></i></a>
                    </div>
                </aside>
            </div>
            <div class="col-sm-4">
                <aside id="ci-instagram-feed-2" class="ci-instagram-feed widget group">
                    <h3 class="widget-title">Instagram</h3>
                    <div loading="lazy" data-mc-src="dae30a78-b1cb-4bab-b29a-00962c17b8e4#instagram"></div>

                    <script src="https://cdn2.woxo.tech/a.js#62f160aa4e9acadeedcec13c" async data-usrc>
                    </script>

                </aside>
            </div>
            <div class="col-sm-4">
                <aside id="ci_twitter_widget-2" class="widget_ci_twitter_widget widget group">
                    <h3 class="widget-title">Twitter</h3>
                    <div class="citwitterwidget2  tul">
                        <!-- <ul>
                            <li><span>You don't need a plugin for that #12: Prevent the checkout process if the customer has pending payments.… <a href="https://t.co/ZNClKAyQsf">https://t.co/ZNClKAyQsf</a></span> <a class="twitter-time" href="https://twitter.com/CSSIgniter/statuses/1493876549518606336">4 days ago</a></li>
                            <li><span>You don't need a plugin for that #11: Change the price display on variable products. #WooCommerce<a href="https://t.co/DwgXVfKWX4">https://t.co/DwgXVfKWX4</a></span> <a class="twitter-time" href="https://twitter.com/CSSIgniter/statuses/1485544246182617088">27 days ago</a></li>
                            <li><span>Building magazine websites with the full site editor and the upcoming pattern explorer will be fun again. <a href="https://t.co/fkxWyoOuvU">https://t.co/fkxWyoOuvU</a></span> <a class="twitter-time" href="https://twitter.com/CSSIgniter/statuses/1473334293774618629">2 months ago</a></li>
                            <li><span>You don't need a plugin for that #11: Display a notice on the single #WooCommerce product page.<a href="https://t.co/7xnOSVEvTJ">https://t.co/7xnOSVEvTJ</a></span> <a class="twitter-time" href="https://twitter.com/CSSIgniter/statuses/1471795092797235208">2 months ago</a></li>
                        </ul> -->
                        <div style="height: 360px;overflow: scroll;overflow-x: hidden;">

                            <a class="twitter-timeline dark" href="https://twitter.com/oh_holykane?ref_src=twsrc%5Etfw">Tweets by oh_holykane</a>
                            <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                        </div>
                    </div>
                </aside>
            </div>
        </div>
    </div>
    <div class="container footer-credits">
        <div class="row">
            <div class="col-xs-12">
                <p> - A theme by CSSIgniter.com</p>
            </div>
        </div>
    </div>
</footer>

templates/layouts/header.html
{% load static %}
{% load shop_tags %}
{% load pages_tag %}
{% with request|get_header as header %}

<header id="header">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-3">

                <h1 class="site-logo imglogo"><a href="/"><img src="{{header.logo.url}}" alt="Holykane - Solo Artist" data-rjs="{{header.logo.url}}" /></a></h1>
            </div>
            <div class="col-md-8 col-sm-9">
                <nav class="nav-secondary-wrap">
                    <ul class="nav-secondary">

                        {% if not user.is_authenticated %}


                        <li id="menu-item-84" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-84"><a href="{% url 'account_login' %}">Login <i class="fa fa-sign-in" aria-hidden="true"></i> </a></li>
                        {% else %}
                        <li id="menu-item-84" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-84"><a href="/my-account">My Account</a></li>
                        {% endif %}
                        {% with request|get_user_cart as cart %}

                        {% if cart.count >= 1 %}
                        <li id="menu-item-85" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-85"><a href="{% url 'shop:checkout' %}">Checkout</a></li>


                        <li>
                            <div class="cart-head"> Shopping Bag: <a href="{% url 'shop:cart' %}"> <b>{{cart.count}} items</b> <span class="cart-price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol"></span>{{ cart.total_sum }}</bdi></span></span> </a></div>
                        </li>
                        {% else %}
                        <li>
                            <div class="cart-head"> Shopping Bag: <a href="{% url 'shop:cart' %}"> <b>{{cart.count}} items</b> <span class="cart-price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>{{ cart.total_sum }}</bdi></span></span> </a></div>
                        </li>
                        {% endif %}

                        {% endwith %}

                    </ul>
                </nav>
                <nav id="nav">
                    <ul id="navigation" class="group">
                        <li id="menu-item-26" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-6 current_page_item menu-item-26"><a href="/" aria-current="page">Home</a></li>
                        <li id="menu-item-25" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-25"><a href="{% url 'discography:all' %}">Discography</a>
                            <ul class="sub-menu">
                                <li id="menu-item-149" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-149"><a href="{% url 'discography:masonry' %}">Discography – Masonry</a></li>
                                <li id="menu-item-147" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-147"><a href="{% url 'discography:all' %}">Discography – All</a></li>
                            </ul>
                        </li>
                        <li id="menu-item-24" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-24"><a href="/events">Events</a>
                            <ul class="sub-menu">
                                <li id="menu-item-116" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-116"><a href="{% url 'events:events-masonry' %}">Events Masonry</a></li>
                                <li id="menu-item-118" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-118"><a href="{% url 'events:events-all' %}"> Events - All</a></li>
                            </ul>
                        </li>
                        <li id="menu-item-27" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-27"><a href="{% url 'media:gallery-masonry' %}">Media</a>
                            <ul class="sub-menu">
                                <li id="menu-item-22" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-22"><a href="{% url 'media:gallery-stapel' %}">Galleries – Stapel</a></li>
                                <li id="menu-item-126" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-126"><a href="{% url 'media:gallery-masonry' %}">Galleries – Masonry</a></li>

                                <li id="menu-item-136" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-136"><a href="{% url 'media:video-masonry' %}">Videos Masonry</a></li>
                            </ul>
                        </li>
                        <li id="menu-item-87" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-87"><a href="/shop">Shop</a></li>
                        <li id="menu-item-33" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-33"><a href="/blog">Blog</a></li>
                        <li id="menu-item-32" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-32"><a href="/contact">Contact</a></li>
                    </ul>
                </nav>
                <div id="mobilemenu"></div>
            </div>
        </div>
    </div>
</header>{% endwith %}

templates/layouts/products_list.html
{% load static %}
{% load disco_tags %}



<main id="main">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="shop-actions group">
                    <div class="actions">

                        <p class="woocommerce-result-count"> Showing all {{products | length}} Products </p>
                        <div class="product-number"> <span>View:</span>
                            {% for page in paginator.page_range %}

                            <a class="paginatorbtn" href="?&flt=True&paged={{page}}">{{page}}</a>
                            {% endfor %}

                            <!-- <a href="?view=all">All</a> -->
                        </div><br><small> page {{page}} of {{paginator.num_pages}} page(s)</small>
                    </div>
                    <div class="woocommerce-notices-wrapper"></div>
                    <form class="woocommerce-ordering" id="sort_form" method="get">
                        {% csrf_token %}
                        <select name="orderby" aria-label="Shop order">
                            <option value="{{orderby}}" selected='selected'>{{orderby}} sorting</option>
                            <option value="popularity">Sort by popularity</option>
                            <option value="rating">Sort by average rating</option>
                            <option value="date">Sort by latest</option>
                            <option value="price">Sort by price: low to high</option>
                            <option value="price-desc">Sort by price: high to low</option>
                        </select> <input type="hidden" name="paged" value="1" />
                        <!-- <button type="submit" hidden></button> -->
                    </form>
                </div>
                <div class="product-list item-list row">

                    {% include "snippets/products.html" %}
                </div>
            </div>
            <div class="col-md-4">
                <div id="sidebar">
                    <aside id="woocommerce_product_search-2" class="woocommerce widget_product_search widget group">
                        <h3 class="widget-title">Search Products</h3>
                        <form role="search" method="get" class="woocommerce-product-search searchform" action="{% url 'discography:search' %}">
                            <div> <label class="screen-reader-text" for="woocommerce-product-search-field-0">Search for:</label> <input type="search" id="woocommerce-product-search-field-0" class="search-field" placeholder="Search products&hellip;" value="" name="q" /> <button class="searchsubmit" type="submit" value="Search"><i class="fa fa-search"></i><span class="screen-reader-text">Search</span></button> <input type="hidden" name="post_type" value="product" /></div>
                        </form>
                    </aside>
                    <aside id="woocommerce_price_filter-2" class="woocommerce widget_price_filter widget group">
                        <h3 class="widget-title">Filter by price</h3>
                        <form method="post" id="price_form">
                            {% csrf_token %}

                            <div class="price_slider_wrapper">
                                <div class="price_slider" style="display:none;"></div>
                                <div class="price_slider_amount" data-step="10"> <input type="text" id="min_price" name="min_price" value="{{min_price}}" data-min="{{min_price}}" placeholder="Min price" /> <input type="text" id="max_price" name="max_price" value="{{max_price}}" data-max="{{max_price}}" placeholder="Max price" />
                                    <button type="submit" class="button" id="price_btn">Filter <i class="fa fa-filter" aria-hidden="true"></i>
                                    </button>
                                    <div class="price_label" style="display:none;"> Price: <span class="from"></span> &mdash; <span class="to"></span></div>
                                    <div class="clear " id="clear_flt" title="Clear " style="float:right;margin-top:13px;font-size:15px;cursor:pointer">
                                        <i class="fa fa-repeat" aria-hidden="true"></i>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </aside>
                    <aside id="woocommerce_products-2" class="woocommerce widget_products widget group">
                        <h3 class="widget-title">Products</h3>
                        <ul class="product_list_widget">
                            {% for prd in otherProducts %}

                            <li class="media">
                                <div class="media-thumb"> <a href="{{prd.get_shop_url}}" title="Wheresoever you go"> <img width="438" height="438" src="{{prd.cover.url}}" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" loading="lazy" srcset="{{prd.cover.url}} 438w, {{prd.cover.url}} 300w, 
                                                        {{prd.cover.url}} 150w,
                                                        {{prd.cover.url}} 100w,
                                                        {{prd.cover.url}} 110w" sizes="(max-width: 438px) 100vw, 438px" /> </a></div>
                                <div class="media-content"> <a class="media-title" href="{{prd.get_shop_url}}"> {{prd.title}} </a>
                                    {% if prd.discount_price %}

                                    <p class="price"> <del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi>
                                                    {{prd.price}}</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi>
                                                    {{prd.discount_price}}</bdi></span></ins></p>
                                    {% else %}
                                    {{prd.price}}</bdi></span></ins></p>

                                    {% endif %}

                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</main>


{% block js %}
<script>


    jQuery('#price_btn').on('click', (e) => {
        e.preventDefault()
        jQuery('#main').load(window.location.toString() + '?&flt=True&', jQuery('#price_form').serialize())
    })

    jQuery('#sort_form').on('change', (e) => {
        e.preventDefault()
        jQuery('#main').load(window.location.toString() + '?&flt=True&', jQuery('#sort_form').serialize())

    })

    jQuery('#clear_flt').on('click', (e) => {
        e.preventDefault()
        jQuery('#main').load(window.location.toString() + '?&clr=True')

    })

    for (let index = 0; index < jQuery('.paginatorbtn').length; index++) {
        const element = jQuery('.paginatorbtn')[index];
        jQuery(element).on('click', (e) => {
            e.preventDefault()
            jQuery('#main').load(window.location.toString() + jQuery(element).attr('href'))

        })

    }







</script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-includes/js/jquery/ui/core.min-1.12.1.js" %}' id='jquery-ui-core-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-includes/js/jquery/ui/mouse.min-1.12.1.js" %}' id='jquery-ui-mouse-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-includes/js/jquery/ui/slider.min-1.12.1.js" %}' id='jquery-ui-slider-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/plugins/woocommerce/assets/js/jquery-ui-touch-punch/jquery-ui-touch-punch.min-5.0.1.js" %}' id='wc-jquery-ui-touchpunch-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/plugins/woocommerce/assets/js/accounting/accounting.min-0.4.2.js" %}' id='accounting-js' defer></script>
<script type='text/javascript' id='wc-price-slider-js-extra'>/* <![CDATA[ */ var woocommerce_price_slider_params = { "currency_format_num_decimals": "0", "currency_format_symbol": "$", "currency_format_decimal_sep": ".", "currency_format_thousand_sep": ",", "currency_format": "%s%v" }; /* ]]> */</script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/plugins/woocommerce/assets/js/frontend/price-slider.min-5.0.1.js" %}' id='wc-price-slider-js' defer></script>

{% endblock js %}