blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import blogDetail, byCategory, add_comment, index

app_name = 'blog'
urlpatterns = [
    path('<date>/<slug>/', blogDetail, name='blog-detail'),
    path('category/<title>/', byCategory, name='by-category'),
    path('add-comment/<blog_id>',
         add_comment, name='add-comment'),
    path('', index, name='home'),
]

discography/urls.py
from django.contrib import admin
from django.urls import path, include

from discography.views import filter_products, remove_from_wish, remove_from_cart, discoMasonary, discoAll, songDetail, index, add_toFav, productDetail, shop, searched, add_to_cart, products_by_category, add_review_url, update_downloads, update_streams


app_name = 'discography'
urlpatterns = [
    path('shop/', shop, name='shop'),
    path('p/<pk>/<slug>', productDetail, name='product-detail'),
    path('album/<pk>/<slug>', songDetail, name='album-detail'),
    path('album/p/search/', searched, name='search'),
    path('album/p/add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('album/p/remove-from-cart/<slug>/',
         remove_from_cart, name='remove-from-cart'),
    path('album/p/add-review/<product_id>',
         add_review_url, name='add-review'),
    path('album/products-by-category/<category>/',
         products_by_category, name='products-by-category'),
    path('track/update-streams/<pk>/', update_streams, name='update-streams'),
    path('track/update-downloads/<pk>/',
         update_downloads, name='update-downloads'),
    path('track/favourite/<album_pk>/<song_pk>/',
         add_toFav, name='add-to-fav'),
    path('', index, name='home'),
    path('p/filter/', filter_products, name='product-filter'),
    path('masonry/', discoMasonary, name='masonry'),
    path('all', discoAll, name='all'),
    path('remove-from-wish/<type>/<pk>/',
         remove_from_wish, name='remove-from-wish'),

]

kaneweb/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('discography/', include('discography.urls', namespace='discography')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('artist-media/', include('media.urls', namespace='media')),
    path('events/', include('events.urls', namespace='events')), ]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/snippets/album-sidebar.html
{% load disco_tags %}
{% load blog_tags %}

<div class="sidebar">
    {% with request|get_latest_EP as latest_album %}

    <aside id="ci-tracklisting-3" class="widget_ci-tracklisting widget group">
        <div class="widget-wrap ">
            <h3 class="widget-title">LATEST EP</h3>
            <div class="row">
                <div class=" col-xs-12"> <a class="item-hold" href="{{latest_album.get_absolute_url}}">
                        <figure class="item-thumb"> <img width="750" height="750" src="{{latest_album.cover.url}}" class="attachment-ci_square size-ci_square wp-post-image" alt="" loading="lazy" srcset="{{latest_album.cover.url}} 
                        750w, {{latest_album.cover.url}} 300w, {{latest_album.cover.url}} 150w, {{latest_album.cover.url}} 100w, {{latest_album.cover.url}} 110w, {{latest_album.cover.url}} 560w" sizes="(max-width: 750px) 100vw, 750px" /></figure>
                    </a><a class="btn item-btn" href="{{latest_album.get_absolute_url}}">Read More »</a></div>
                <div class=" col-xs-12">

                    <ul class="tracklisting">
                        {% for track in latest_album.songs.all %}

                        <li class="group track" id="player-73_1"> <a href="{{track.audio.url}}" class="sm2_link"><i class="fa fa-play"></i></a>
                            <div class="track-info">
                                <p class="item-title-main">{{track.title}}</p>
                                <p class="item-byline">{{track.version}} &nbsp;</p> <span class="track-no">{{forloop.counter}}</span>
                            </div>
                        </li>
                        {% endfor %}

                    </ul>
                </div>
            </div>
        </div>
    </aside>
    {% endwith %}

    <aside id="search-2" class="widget_search widget group">
        <h3 class="widget-title">Search</h3>
        <form action="{% url 'discography:search' %}" method="get" role="search" class="searchform">
            <div> <label for="s" class="screen-reader-text">Search for:</label> <input type="text" id="s" name="q" value="" placeholder="SEARCH"> <button type="submit" value="GO" class="searchsubmit"><i class="fa fa-search"></i></button></div>
        </form>
    </aside>
    <aside id="categories-2" class="widget_categories widget group">
        <h3 class="widget-title">Categories</h3>
        <ul>
            {% with request|get_blog_categories as categories %}

            {% for category in categories %}

            <li class="cat-item cat-item-24"><a href="{{category.get_absolute_url}}">{{category.title}}</a></li>
            {% endfor %}
            {% endwith %}

        </ul>
    </aside>
    <aside id="socials-ignited-3" class="widget_socials_ignited widget group">
        <h3 class="widget-title">Social Me</h3>
        <div class="ci-socials-ignited ci-socials-ignited-fa"><a href="https://www.instagram.com/holy_kane/" target="_blank" rel="nofollow"><i class="fa fa-instagram"></i></a>
            <a href="#" target="_blank" rel="nofollow"><i class="fa fa-linkedin">
                </i></a><a href="#" target="_blank" rel="nofollow"><i class="fa fa-facebook"></i></a>
            <a href="https://twitter.com/oh_holykane" target="_blank" rel="nofollow"><i class="fa fa-twitter"></i></a><a href="https://www.youtube.com/channel/UCqaX45IOEo89P1EMhr0g8oA" target="_blank" rel="nofollow"><i class="fa fa-youtube"></i></a>
        </div>

    </aside>
    <aside id="ci-top-tracks-2" class="widget_ci-top-tracks widget group">

        <div class="widget-wrap ">
            {% with request|get_user_favourites as favourites %}

            {% if favourites %}


            <h3 class="widget-title">My Favorite Tracks</h3>
            <div class="row">
                <div class="col-xs-12">
                    <ul class="tracklisting tracklisting-top">

                        {% for fav in favourites %}

                        {% for song in fav.songs.all %}

                        {% include "snippets/track.html" with track=song album=fav.album %}
                        {% endfor %}

                        {% endfor %}



                    </ul>
                </div>
            </div>
            {% endif %}

            {% endwith %}

        </div>
    </aside>
</div>

templates/snippets/discography-sidebar.html
<div class="col-sm-4">
    <div id="sidebar">
        <aside id="woocommerce_product_search-2" class="woocommerce widget_product_search widget group">
            <h3 class="widget-title">Search Products</h3>
            <form role="search" method="get" class="woocommerce-product-search searchform" action="{% url 'discography:search' %}">
                <div> <label class="screen-reader-text" for="woocommerce-product-search-field-0">Search for:</label> <input type="search" id="woocommerce-product-search-field-0" class="search-field" placeholder="Search products&hellip;" value="" name="q" /> <button class="searchsubmit" type="submit" value="Search"><i class="fa fa-search"></i><span class="screen-reader-text">Search</span></button>
                    <input type="hidden" name="post_type" value="product" />
                </div>
            </form>
        </aside>
        <aside id="woocommerce_products-2" class="woocommerce widget_products widget group">
            <h3 class="widget-title">Products</h3>
            <ul class="product_list_widget">
                {% for prd in products %}

                <li class="media">
                    <div class="media-thumb"> <a href="{{prd.get_shop_url}}" title="Wheresoever you go"> <img width="438" height="438" src="{{prd.cover.url}}" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" loading="lazy" srcset="{{prd.cover.url}} 438w, {{prd.cover.url}} 300w, 
                                {{prd.cover.url}} 150w,
                                {{prd.cover.url}} 100w,
                                {{prd.cover.url}} 110w" sizes="(max-width: 438px) 100vw, 438px" /> </a></div>
                    <div class="media-content"> <a class="media-title" href="{{prd.get_shop_url}}"> {{prd.title}} </a>
                        {% if prd.discount_price %}

                        <p class="price"> <del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi>
                                        {{prd.price}}</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi>
                                        {{prd.discount_price}}</bdi></span></ins></p>
                        {% else %}
                        {{prd.price}}</bdi></span></ins></p>

                        {% endif %}

                    </div>
                </li>
                {% endfor %}

            </ul>
        </aside>
    </div>
</div>

templates/snippets/foot.html
{% load static %}
{% include "layouts/footer.html" %}
</div>
<div class="player-main-cont" style="position: fixed;margin: 10px;bottom: 0;left: 0;z-index: 10;">
    {% include "snippets/player.html" %}

</div>
<script type="text/javascript">(function () {
        var c = document.body.className;
        c = c.replace(/woocommerce-no-js/, 'woocommerce-js');
        document.body.className = c;
    })();</script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-includes/js/dist/vendor/regenerator-runtime.min-0.13.7.js" %}' id='regenerator-runtime-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-includes/js/dist/vendor/wp-polyfill.min-3.15.0.js" %}' id='wp-polyfill-js' defer></script>
<script type='text/javascript' id='contact-form-7-js-extra'>/* <![CDATA[ */ var wpcf7 = { "api": { "root": "https:\/\/www.cssigniter.com\/vip\/solo\/wp-json\/", "namespace": "contact-form-7\/v1" }, "cached": "1" }; /* ]]> */</script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/plugins/contact-form-7/includes/js-5.5.4.js" %}' id='contact-form-7-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/plugins/woocommerce/assets/js/jquery-blockui/jquery.blockUI.min-2.7.0-wc.6.1.1.js" %}' id='jquery-blockui-js' defer></script>
<script type='text/javascript' id='wc-add-to-cart-js-extra'>/* <![CDATA[ */ var wc_add_to_cart_params = { "ajax_url": "\/vip\/solo\/wp-admin\/admin-ajax.php", "wc_ajax_url": "\/vip\/solo\/?wc-ajax=%%endpoint%%", "i18n_view_cart": "View cart", "cart_url": "https:\/\/www.cssigniter.com\/vip\/solo\/cart\/", "is_cart": "", "cart_redirect_after_add": "no" }; /* ]]> */</script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/plugins/woocommerce/assets/js/frontend/add-to-cart.min-6.1.1.js" %}' id='wc-add-to-cart-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/plugins/woocommerce/assets/js/js-cookie/js.cookie.min-2.1.4-wc.6.1.1.js" %}' id='js-cookie-js' defer></script>
<script type='text/javascript' id='woocommerce-js-extra'>/* <![CDATA[ */ var woocommerce_params = { "ajax_url": "\/vip\/solo\/wp-admin\/admin-ajax.php", "wc_ajax_url": "\/vip\/solo\/?wc-ajax=%%endpoint%%" }; /* ]]> */</script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/plugins/woocommerce/assets/js/frontend/woocommerce.min-6.1.1.js" %}' id='woocommerce-js' defer></script>
<script type='text/javascript' id='wc-cart-fragments-js-extra'>/* <![CDATA[ */ var wc_cart_fragments_params = { "ajax_url": "\/vip\/solo\/wp-admin\/admin-ajax.php", "wc_ajax_url": "\/vip\/solo\/?wc-ajax=%%endpoint%%", "cart_hash_key": "wc_cart_hash_6ce56b62fb0316e469fbf924f683d7bd", "fragment_name": "wc_fragments_6ce56b62fb0316e469fbf924f683d7bd", "request_timeout": "5000" }; /* ]]> */</script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min-6.1.1.js" %}' id='wc-cart-fragments-js' defer></script>
<script type='text/javascript' src='{% static "wp-includes/js/comment-reply.min.js" %}' id='comment-reply-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/themes/chords/js/superfish.js" %}' id='jquery-superfish-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/themes/chords/js/jquery.mmenu.min.all.js" %}' id='jquery-mmenu-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/themes/chords/js/jquery.flexslider.js" %}' id='jquery-flexslider-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/themes/chords/js/jquery.matchHeight-min.js" %}' id='jquery-matchHeight-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/themes/chords/panel/scripts/jquery.fitvids-2.7.1.js" %}' id='jquery-fitVids-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/themes/chords/js/jquery.prettyPhoto.min-3.1.6.js" %}' id='prettyPhoto-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/themes/chords/js/jquery.isotope.js" %}' id='jquery-isotope-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/themes/chords/js/parallax.min-1.3.1.js" %}' id='parallax-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/themes/chords/js/jquery.shoutcast.min-2.7.1.js" %}' id='jquery-shoutcast-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/themes/chords/js/soundmanager2-2.97.js" %}' id='soundmanager-core-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/themes/chords/js/inlineplayer-2.97.js" %}' id='inline-player-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/themes/chords/js/ci_audioplayer-2.97.js" %}' id='ci-audioplayer-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/themes/chords/js/jquery.stapel.js" %}' id='stapel-js' defer></script>
<script type='text/javascript' id='ci-front-scripts-js-extra'>/* <![CDATA[ */ var ThemeOption = { "theme_url": "https:\/\/www.cssigniter.com\/vip\/solo\/wp-content\/themes\/chords", "slider_auto": "", "swfPath": "https:\/\/www.cssigniter.com\/vip\/solo\/wp-content\/themes\/chords\/js\/swf\/", "slider_autoslide": "1", "slider_effect": "fade", "slider_direction": "horizontal", "slider_duration": "600", "slider_speed": "5000" }; /* ]]> */</script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/themes/chords/js/scripts-2.7.1.js" %}' id='ci-front-scripts-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/themes/chords/panel/components/retinajs/dist/retina-2.7.1.js" %}' id='retinajs-js' defer></script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/plugins/ci-videos/assets/js/ci-videos-scripts-1.0.js" %}' id='ci-videos-scripts-js' defer></script>
<script type='text/javascript' src='{% static "wp-includes/js/wp-embed.min.js" %}' id='wp-embed-js' defer></script>

<script type='text/javascript' id='wc-single-product-js-extra'>/* <![CDATA[ */ var wc_single_product_params = { "i18n_required_rating_text": "Please select a rating", "review_rating_required": "yes", "flexslider": { "rtl": false, "animation": "slide", "smoothHeight": true, "directionNav": false, "controlNav": "thumbnails", "slideshow": false, "animationSpeed": 500, "animationLoop": false, "allowOneSlide": false }, "zoom_enabled": "", "zoom_options": [], "photoswipe_enabled": "", "photoswipe_options": { "shareEl": false, "closeOnScroll": false, "history": false, "hideAnimationDuration": 0, "showAnimationDuration": 0 }, "flexslider_enabled": "" }; /* ]]> */</script>
<script type='text/javascript' src='{% static "wp-content/cache/busting/2/vip/solo/wp-content/plugins/woocommerce/assets/js/frontend/single-product.min-6.1.1.js" %}' id='wc-single-product-js' defer></script>


{% block js %}

{% endblock js %}
<script>

    setTimeout(() => {

        jQuery('.alert').fadeOut(100)

    }, 3000)


    for (let index = 0; index < jQuery('.add_to_cart').length; index++) {
        const element = jQuery('.add_to_cart')[index];
        jQuery(element).on('click', (e) => {
            var crt_url = e.target.getAttribute('data-url')
            jQuery('body').load(crt_url)
        })
    }

    for (let index = 0; index < jQuery('.remove_from_cart').length; index++) {
        const element = jQuery('.add_to_cart')[index];
        jQuery(element).on('click', (e) => {
            var crt_url = e.target.getAttribute('data-url')
            jQuery('body').load(crt_url)
        })
    }

    for (let index = 0; index < jQuery('.remove-from-wish').length; index++) {
        const element = jQuery('.remove-from-wish')[index];
        jQuery(element).on('click', (e) => {
            e.preventDefault()
            var crt_url = e.target.getAttribute('data-url')
            jQuery('body').load(crt_url)
        })
    }

</script>
</body>
<!-- Mirrored from www.cssigniter.com/vip/solo/ by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 08 Aug 2022 11:15:20 GMT -->

</html>

<!-- This website is like a Rocket, isn't it? Performance optimized by WP Rocket. Learn more: https://wp-rocket.me - Debug: cached@1645348143 -->

templates/snippets/latest_album_snippet.html
{% load disco_tags %}
{% with request|get_latest_EP as latest_album %}


<div class="widget-wrap ">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h2 class="section-title">Latest EP</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 col-xs-12"> <a class="item-hold" href="{{latest_album.get_absolute_url}}">
                    <figure class="item-thumb"> <img width="750" height="750" src="{{latest_album.cover.url}}" class="attachment-ci_square size-ci_square wp-post-image" alt="" loading="lazy" srcset="{{latest_album.cover.url}} 750w, {{latest_album.cover.url}} 300w, {{latest_album.cover.url}} 150w, {{latest_album.cover.url}} 100w, {{latest_album.cover.url}} 110w, {{latest_album.cover.url}} 560w" sizes="(max-width: 750px) 100vw, 750px" /></figure>
                </a><a class="btn item-btn" href="{{latest_album.get_absolute_url}}">Read More »</a></div>
            <div class="col-sm-8 col-xs-12">
                <ul class="tracklisting">

                    {% for track in latest_album.songs.all %}

                    {% include "snippets/track.html" with album=latest_album %}

                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>
</div>
{% endwith %}

templates/snippets/newsletter_sn.html
<div class="inner-widget-area">
    <section id="ci-newsletter-3" class="widget group widget_ci-newsletter">
        <div class="widget-wrap ">
            <div class="container">
                <form action="{% url 'newsletter_signin' %}" method="post" class="ci-newsletter-form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-5 col-sm-12">
                            <label for="e_id">Subscribe to our newsletter</label>
                            <span>Stay up to date!</span>
                        </div>

                        <div class="col-md-7 col-sm-12">
                            <div class="input-group">
                                <input type="email" name="email" id="e_id" placeholder="Your e-mail">
                                <button type="submit" class="btn">Subscribe now</button>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="hidden1" value="value1"><input type="hidden" name="hidden2" value="value2">
                </form>
            </div><!-- /container -->
        </div><!-- /widget-wrap -->
    </section>
</div>

templates/snippets/only_album_snippet.html
{% load disco_tags %}

<div class="col-md-4 col-sm-5 ">
    <div class="sidebar">
        <aside id="ci-tracklisting-4" class="widget_ci-tracklisting widget group">
            <div class="widget-wrap ">
                <h3 class="widget-title">Latest EP</h3>
                <div class="row">
                    {% with request|get_latest_EP as latest_album %}

                    <div class=" col-xs-12"> <a class="item-hold" href="{{latest_album.get_absolute_url}}">
                            <figure class="item-thumb"> <img width="750" height="750" src="{{latest_album.cover.url}}" class="attachment-ci_square size-ci_square wp-post-image" alt="" loading="lazy" srcset=" 
                            {{latest_album.cover.url}} 750w, {{latest_album.cover.url}} 300w, {{latest_album.cover.url}} 150w,  {{latest_album.cover.url}}100w, 
                             {{latest_album.cover.url}} 110w,  {{latest_album.cover.url}} 560w" sizes="(max-width: 750px) 100vw, 750px" /></figure>
                        </a><a class="btn item-btn" href="{{latest_album.get_absolute_url}}">Read More »</a></div>
                    <div class=" col-xs-12">
                        <ul class="tracklisting">
                            {% for track in latest_album.songs.all %}
                            {% include "snippets/track.html" with album=latest_album %}
                            {% endfor %}
                        </ul>
                    </div>
                    {% endwith %}
                </div>
            </div>
        </aside>
    </div>
</div>

templates/snippets/products.html
{% for product in products %}


<div class="col-md-6 col-sm-6 col-xs-12">
    <div class="item product type-product post-104 status-publish first instock product_cat-albums has-post-thumbnail sale shipping-taxable purchasable product-type-simple"><a href="{{product.get_shop_url}}">
            <figure class="item-thumb"> <img width="750" height="743" src="{{product.cover.url}}" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" loading="lazy" srcset="
            {{product.cover.url}} 750w, {{product.cover.url}} 150w, {{product.cover.url}} 300w, {{product.cover.url}} 100w, {{product.cover.url}} 110w, {{product.cover.url}} 560w" sizes="(max-width: 750px) 100vw, 750px" /></figure>
        </a>
        <div class="item-info">
            <p class="item-title-main"> {{product.title}}</p>
            <p class="item-byline">
                {% if product.available_discount %}

                <span class="price"><del aria-hidden="true">
                        <span class="woocommerce-Price-amount amount">
                            <bdi><span class="woocommerce-Price-currencySymbol"></span>{{product.price}}</bdi>
                        </span></del>
                </span>
                <span class="woocommerce-Price-amount amount"><bdi>
                        {{product.discount_price}}</bdi>
                </span> <span class="onsale">Sale!</span>

                {% else %}




                <bdi><span class="woocommerce-Price-currencySymbol"></span>{{product.price}}</bdi></span></del>

                {% endif %}

            </p>
        </div><a class="btn item-btn" href="{{product.get_shop_url}}"> View More </a>
    </div>
</div>
{% empty %}
<center>
    <h3 style="font-family: 'Courier New', Courier, monospace;">Nothing found</h3>
    <a href="/shop">Continue Shopping <i class="fa fa-shopping-bag" aria-hidden="true"></i></a>

</center>
{% endfor %}

templates/snippets/track.html
{% load pages_tag %}
{% if detail == True %}
{% with request|check_fav:song.id as is_fav %}

<li class="group track" id="player-73_5"> <a href="javascript:void()" onclick="handlePlay('{{song.get_serialized}}','{{is_fav}}', 
'{{song.get_update_streams_url}}',`{% url 'discography:add-to-fav' album.pk song.pk %}`)" data-pk="{{song.pk}}" class="sm2_link li-playbtn playbtn-{{song.pk}}">
        <span id="icon">
            <!-- <i class="fa fa-play"> </i> -->
            <i class="fa fa-pause"></i>
        </span>
    </a>
    <div class="track-info">
        <p class="item-title-main">{{song.title}}</p>
        <p class="item-byline">{{song.version}} &nbsp;</p>
        <ul class="track-buttons">

            {% if song.lyrics %}


            <li> <a data-rel="prettyPhoto" href="#{{song.title}}-lyrics-5" title="{{song.title}} Lyrics" class="btn btn-xs"><i class="fa fa-book"></i> <span>Lyrics</span> </a>
                <div id="{{song.title}}-lyrics-5" class="track-lyrics-hold" style="display:none;">
                    {{song.lyrics}}</div>
            </li> {% endif %}

            {% if song.downloadable %}

            <li> <a href="{{song.get_update_downloads_url}}" class="btn btn-xs inline-exclude"><i class="fa fa-download"></i> <span>Download track</span> </a></li>
            {% endif %}

        </ul> <span class="track-no">{{forloop.counter}}</span>
    </div>
</li>
{% endwith %}
{% else %}
{% with request|check_fav:track.id as is_fav %}

<li class="group track pause" id="player-ci-top-tracks-2_1"> <a href="javascript:void()" data-pk="{{track.pk}}" onclick="handlePlay('{{track.get_serialized}}','{{is_fav}}', '{{track.get_update_streams_url}}',`{% url 'discography:add-to-fav' album.pk track.pk %}`)" class="sm2_link li-playbtn playbtn-{{track.pk}}">
        <span id="icon">

            <!-- <i class="fa fa-play"></i> -->
            <i class="fa fa-pause"></i>

        </span>
    </a>
    <div class="track-info">
        <p class="item-title-main">{{track.title}}</p>
        <p class="item-byline">{{track.version}} &nbsp;</p><span class="track-no">{{forloop.counter}}</span>
    </div>
</li>
{% endwith %}

{% endif %}