blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import blogDetail, byCategory, add_comment, index

app_name = 'blog'
urlpatterns = [
    path('<date>/<slug>/', blogDetail, name='blog-detail'),
    path('category/<title>/', byCategory, name='by-category'),
    path('add-comment/<blog_id>',
         add_comment, name='add-comment'),
    path('', index, name='home'),
]

kaneweb/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('discography/', include('discography.urls', namespace='discography')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('artist-media/', include('media.urls', namespace='media')),
    path('events/', include('events.urls', namespace='events')), ]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, re_path
from .views import order, order_detail, payment_status, payment,  cart, checkout, wishlist

app_name = 'shop'

urlpatterns = [
    path('order/', order, name='order'),
    path('order-detail/<code>/', order_detail, name='order-detail'),
    path('order/<order_code>/',
         payment_status, name='payment-status'),
    path('cart/', cart, name='cart'),
    path('wishlist/', wishlist, name='wishlist'),
    path('checkout/', checkout, name='checkout'),
    path('payment/<type>/<order_id>/', payment, name='payment'),
]

shop/models.py
import json
import random
import string
from django.conf import settings
from django.db import models
from djmoney import money
# Create your models here.
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField
from django_countries.fields import CountryField
from djmoney.models.fields import MoneyField
from django.db.models.signals import post_save
from django.core import serializers
from discography.models import Song, Genre, ALBUM_CATEGORIES
from core.models import SHIPPING_FEE
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.


class Favourite(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='favourite_songs')
    album = models.ForeignKey(
        'Album', on_delete=models.CASCADE, related_name='faved')
    songs = models.ManyToManyField(Song, related_name='favs')
    sessionID = models.CharField(
        max_length=200, null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)  # Date of creation
    updated_on = models.DateTimeField(auto_now=True)  # Date of updation


class FileManager(models.Model):
    name = models.CharField(max_length=100, default='')
    description = models.TextField(max_length=5000)
    type = models.CharField(max_length=10, default='I',
                            choices=(('I', 'Images'), ('V', 'Videos'), ('A', 'Audio'), ('G', 'GIF')))
    created_on = models.DateTimeField(auto_now_add=True)  # Date of creation
    updated_on = models.DateTimeField(auto_now=True)  # Date of updation
    file = models.FileField(upload_to='files/')

    def __str__(self):
        return self.name


class Album(models.Model):
    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
    artist = models.ForeignKey(User, on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    songs = models.ManyToManyField(
        Song, related_name='album')
    release_date = models.DateTimeField()
    cover = models.ImageField(upload_to='album/images/')
    additional_files = models.ManyToManyField(
        FileManager, blank=True, related_name='album_files')
    sku = models.CharField(max_length=222, blank=True, null=True)
    upc = models.CharField(max_length=222, blank=True, null=True)
    price = MoneyField(
        decimal_places=1, default_currency=settings.DEFAULT_MONEY_CURRENCY, max_digits=10)
    discount_price = MoneyField(
        decimal_places=1, default=0.0, default_currency=settings.DEFAULT_MONEY_CURRENCY, max_digits=10)
    record_label = models.CharField(max_length=255)

    shop_link = models.URLField()
    catalog_number = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    description = RichTextUploadingField(config_name='awesome_ckeditor')
    category = models.CharField(max_length=10, choices=ALBUM_CATEGORIES)
    tags = TaggableManager()  # Tags for a Particular Article, You need to install Taggit
    genre = models.ForeignKey(
        Genre, related_name='genre_album', on_delete=models.CASCADE)
    # Keywords to be used in SEO
    keywords = models.CharField(max_length=250, blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)  # Date of creation
    updated_on = models.DateTimeField(auto_now=True)  # Date of updation

    audiomack_link = models.URLField(blank=True, null=True)
    spotify_link = models.URLField(blank=True, null=True)
    itunes_link = models.URLField(blank=True, null=True)
    youtube_link = models.URLField(blank=True, null=True)
    type = models.CharField(max_length=1, choices=(
        ('T', 'Track'), ('M', 'Merch')))

    def __str__(self):
        return self.title

    def get_total_streams(self):

        return sum([sum([item.count for item in song.streams.all()]) for song in self.songs.all()])

    def get_absolute_url(self):
        return reverse("discography:album-detail",  kwargs={'slug': self.slug, 'pk': self.pk})

    def get_category_url(self):
        return reverse("discography:products-by-category",  kwargs={'category': self.get_category_display()})

    def get_shop_url(self):
        return reverse("discography:product-detail", kwargs={'slug': self.slug, 'pk': self.pk})

    def get_add_to_cart_url(self):
        return reverse("discography:add-to-cart", kwargs={'slug': self.slug})

    def get_remove_from_cart_url(self):
        return reverse("discography:remove-from-cart", kwargs={'slug': self.slug})

    def get_add_review_url(self):
        return reverse('discography:add-review', kwargs={'product_id': self.id})

    def get_price(self):
        if self.discount_price.amount >= 1:
            return self.discount_price
        else:
            return self.price

    def is_merch(self):
        if self.category == 'M':
            return True
        else:
            return False

    def is_album(self):
        if self.category == 'A':
            return True
        else:
            return False

    def is_EP(self):
        if self.category == 'E':
            return True
        else:
            return False

    def is_single(self):
        if self.category == 'S':
            return True
        else:
            return False

    def available_discount(self):
        if self.discount_price.amount <= 0 or None:
            return False
        else:
            return True


# Order Item, checks on a particular item if ordered


class Cart(models.Model):
    user = models.ForeignKey(User, null=True,
                             on_delete=models.CASCADE, related_name='carts')
    sessionID = models.CharField(
        max_length=200,  null=True, blank=True)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Album, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_sum_price(self):
        if self.item.discount_price.amount >= 1:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

    def __str__(self):

        if self.user:
            return self.user.username
        if self.sessionID:
            return self.sessionID
        else:
            return f'{self.id}'


# Order Model, Details on the Order made
class Order(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE, blank=True, null=True, related_name='orders')
    ref_code = models.CharField(
        max_length=20, blank=True, unique=True, null=True)
    items = models.ManyToManyField(Cart, related_name='parent_orders')
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(blank=True, null=True)
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)

    status = models.CharField(max_length=3, default='N', choices=(('N', 'None'),
                                                                  ('P', 'Placed'), ('D', 'Delivered'), ('C', 'Shipped'), ('C', 'Cancelled'))

                              )
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    sessionID = models.CharField(
        max_length=200,  null=True, blank=True)

    def __str__(self):

        if self.user:
            return self.user.username
        if self.sessionID:
            return self.sessionID
        else:
            return f'{self.id}'

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_sum_price()
        if self.coupon:
            total -= self.coupon.amount
        return total + SHIPPING_FEE

    def get_subtotal(self):
        sub_total = self.get_total() - SHIPPING_FEE

        return sub_total

    def shipping_fee(self):
        return SHIPPING_FEE

    def get_absolute_url(self):
        return reverse('shop:order-detail', kwargs={'code': self.ref_code})

# Address Model


ADDRESS_CHOICES = (('S', 'Shipping Address'), ('B', 'Billing Address'))


class Address(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE, blank=True, related_name='addresses', null=True)
    state = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)
    email = models.EmailField()
    full_name = models.CharField(max_length=200)
    phone = PhoneNumberField()
    sessionID = models.CharField(
        max_length=200,  null=True, blank=True)

    def __str__(self):

        return self.full_name

    class Meta:
        verbose_name_plural = 'Addresses'


# Payment Model Using stripe
class Payment(models.Model):

shop/forms.py
from django import forms
from .models import Address
from django_countries.widgets import CountrySelectWidget


class BillingAddressesForm (forms.ModelForm):
    field_order = ['email', 'full_name',
                   'country', 'state', 'city', 'apartment_address', 'zip', 'default', ]
    address_type = forms.CharField(
        widget=forms.HiddenInput(attrs={'id': 'adr_type', 'hidden': 'true', 'value': 'B'}))

    class Meta:
        exclude = ['user', 'sessionID']
        model = Address


class ShippingAddressesForm (forms.ModelForm):
    field_order = ['email', 'full_name',
                   'country', 'state', 'city', 'apartment_address', 'zip', 'default', ]
    address_type = forms.CharField(

        widget=forms.HiddenInput(attrs={'id': 'adr_type', 'hidden': 'true', 'value': 'S'}))

    class Meta:
        exclude = ['user', 'sessionID']
        model = Address

templates/shop/order-detail.html
{% extends 'base.html' %}

{% block title %}
Order Detail - {{order.ref_code}} - Solo Artist
{% endblock title %}


{% block content %}

<style>
    .card {
        box-shadow: 0 20px 27px 0 rgb(0 0 0 / 5%);
    }

    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        /* background-color: #fff; */
        background-clip: border-box;
        border: 0 solid rgba(0, 0, 0, .125);
        border-radius: 1rem;
    }

    .text-reset {
        --bs-text-opacity: 1;
        color: inherit !important;
    }

    a {
        color: #5465ff;
        text-decoration: none;
    }



    .cont-order-d {
        font-family: Georgia, 'Times New Roman', Times, serif;
        padding: 10px;

    }
</style>
<div class="container-fluid cont-order-d">

    <div class="container">
        <!-- Title -->
        <div class="d-flex justify-content-between align-items-center py-3">
            <h2 class="h5 mb-0"><a href="#" class="text-muted"></a> Order #{{order.ref_code}}</h2>
        </div>

        <!-- Main content -->
        <div class="row">
            <div class="col-lg-8">
                <!-- Details -->
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="mb-3 d-flex justify-content-between">
                            <div>
                                <span class="me-3">{{order.ordered_date | date}}</span>
                                <span class="me-3">#{{order.ref_code}}</span>
                                <span class="me-3">{{order.payment.get_method_display}}</span>
                                <span class="badge rounded-pill bg-info">{{order.get_status_display}}</span>
                            </div>
                            <div class="d-flex">
                                <button class="btn btn-link p-0 me-3 d-none d-lg-block btn-icon-text"><i class="bi bi-download"></i> <span class="text">Invoice</span></button>
                                <div class="dropdown">
                                    <ul class="dropdown-menu dropdown-menu-end">
                                        <!-- <li><a class="dropdown-item" href="#"><i class="bi bi-pencil"></i> </a></li>
                                        <li><a class="dropdown-item" href="#"><i class="bi bi-printer"></i> Print</a></li> -->
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <table class="table table-borderless">
                            <tbody>
                                {% for cart in order.items.all %}

                                <tr>
                                    <td>
                                        <div class="d-flex mb-2">
                                            <div class="flex-shrink-0">
                                                <img src="{{cart.item.cover.url}}" alt="" width="100" height="100" class="img-fluid">
                                            </div>
                                            <div class="flex-lg-grow-1 ms-3">
                                                <h6 class="small mb-0"><a href="#" class="text-reset">{{cart.item.title}}</a></h6>
                                                <span class="small">Type :{{cart.item.get_type_display}}</span>

                                            </div>
                                        </div>
                                    </td>
                                    <td>Qty. {{cart.quantity}}</td>
                                    <td class="text-end">{{cart.get_final_sum_price}}
                                        <a href="{{cart.item.get_shop_url}}" class=" btn btn-primary">View Item</a>
                                    </td>

                                </tr>
                                {% endfor %}

                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="2">Subtotal</td>
                                    <td class="text-end">{{order.get_subtotal}}</td>
                                </tr>
                                <tr>
                                    <td colspan="2">Shipping</td>
                                    <td class="text-end">{{order.shipping_fee}}</td>
                                </tr>
                                <tr>

                                    {% if order.coupon %}


                                    <td colspan="2">Discount (Code: {{order.coupon.code}})</td>

                                    <td class="text-danger text-end">-{{order.coupon.amount}}</td>
                                    {% endif %}

                                </tr>
                                <tr class="fw-bold">
                                    <td colspan="2">TOTAL</td>
                                    <td class="text-end">{{order.get_total}}</td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
                <!-- Payment -->
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-6">
                                <h3 class="h6">Payment Method</h3>
                                <p>{{order.payment.get_method_display}} <br>

                                    {% if order.payment.status == 's' %}


                                    Total:{{order.payment.amount}} {{order.payment.currency}} <span class="badge bg-success rounded-pill">PAID</span></p>
                                {% endif %}

                            </div>
                            <div class="col-lg-6">
                                <h3 class="h6">Billing address</h3>
                                <address>
                                    <strong>{{order.billing_address.full_name}}</strong><br>
                                    {{order.billing_address.apartment_address}}<br>
                                    {{order.billing_address.state}}, {{order.billing_address.country}}<br>
                                    <abbr title="email">E:</abbr> {{order.billing_address.email}}
                                </address>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <!-- Customer Notes -->
                <div class="card mb-4">
                    <div class="card-body">
                    </div>
                </div>
                <div class="card mb-4">
                    <!-- Shipping information -->
                    <div class="card-body">
                        <h3 class="h6">Shipping Information</h3>
                        <!-- <strong>FedEx</strong> -->
                        <!-- <span><a href="#" class="text-decoration-underline" target="_blank">FF1234567890</a> <i class="bi bi-box-arrow-up-right"></i> </span> -->
                        <hr>
                        <h3 class="h6">Address</h3>
                        <address>
                            <strong>{{order.shipping_address.full_name}}</strong><br>
                            {{order.shipping_address.apartment_address}}<br>
                            {{order.shipping_address.state}}, {{order.shipping_address.country}}<br>
                            <abbr title="email">E:</abbr> {{order.shipping_address.email}}
                        </address>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/shop/order.html
{% extends 'base.html' %}

{% block title %}
Orders - Holykane - Solo Artist
{% endblock title %}


{% block content %}
<style>
    .orders-body {
        background: inherit;
        text-align: center;
        font-family: "Oswald";
    }

    .wrapper {
        margin: auto;
    }

    .product {
        position: relative;

        margin: auto;
        overflow: hidden;
        margin-bottom: 20px;
    }

    .product>div {
        position: relative;
        z-index: 10;
    }

    .product .title {
        background-color: #333;
        color: #fff;
        padding: 10px;
        font-size: 18px;
        z-index: 20;
    }

    .product .text {
        text-align: left;
        width: 49.5%;
        display: inline-block;
        vertical-align: middle;
        color: rgb(233, 220, 220);
        font-weight: 300;
        padding: 20px 0;
    }

    .product .text .code {
        padding: 0 20px;
        font-size: 11px;
        font-weight: 700;
        margin-bottom: 5px;
    }

    .product .text .description {
        padding: 0 20px;
        margin-bottom: 10px;
        color: #757575;
    }

    .product .text .review {
        font-size: 12px;
        padding: 0 20px;
    }

    .product .text .review>span {
        vertical-align: middle;
    }

    .product .text .review>span.star-icon {
        width: 20px;
        height: 20px;
        display: inline-block;
    }

    .product .text .review .star-icon {
        background-image: url(https://cdn4.iconfinder.com/data/icons/small-n-flat/24/star-20.png);
    }

    .product .text .review .star-disable {
        opacity: 0.5;
    }

    .product .text .price {
        padding: 0 20px;
        font-size: 2.5em;
        margin-bottom: 10px;
    }

    .product .text .shop-actions {
        padding: 0 20px;
    }

    .product .text .shop-actions button {
        width: 100%;
        vertical-align: middle;
        background-color: #b32929;
        border: none;
        box-shadow: 0 5px 5px -2px rgba(71, 69, 69, 0.5);
        padding: 5px;
        font-size: 18px;
        font-family: "Oswald";
    }

    .product .preview {
        width: 49.5%;
        display: inline-block;
        vertical-align: middle;
        height: 240px;
    }

    .product .svg {
        position: absolute;
        width: 100%;
        left: 0;
        top: 0;
        height: 100%;
        z-index: 0;
    }

    .product .svg .circle {
        fill: #ccc;
        transform-origin: 50% 50%;
        -webkit-transform: scale(0.8);
        -moz-transform: scale(0.8);
        -ms-transform: scale(0.8);
        -o-transform: scale(0.8);
        transform: scale(0.8);
        -webkit-transition: transform 300ms;
        -moz-transition: transform 300ms;
        -ms-transition: transform 300ms;
        -o-transition: transform 300ms;
        transition: transform 300ms;
    }

    .product .svg .image {
        transform-origin: 50% 50%;
        -webkit-transform: rotate(0);
        -moz-transform: rotate(0);
        -ms-transform: rotate(0);
        -o-transform: rotate(0);
        transform: rotate(0);
        -webkit-transition: transform 300ms;
        -moz-transition: transform 300ms;
        -ms-transition: transform 300ms;
        -o-transition: transform 300ms;
        transition: transform 300ms;
    }

    .product:hover .preview .image {
        -webkit-transform: rotate(20deg);
        -moz-transform: rotate(20deg);
        -ms-transform: rotate(20deg);
        -o-transform: rotate(20deg);
        transform: rotate(20deg);
    }

    .product:hover .preview .circle {
        -webkit-transform: scale(1);
        -moz-transform: scale(1);
        -ms-transform: scale(1);
        -o-transform: scale(1);
        transform: scale(1);
    }
</style>
<div class="container">
    <div class="row">
        <h1 style="text-align: center;">My Orders</h1>
        <div class="orders-body">

            <div class="col-md-8 ">
                <div class="wrapper">
                    {% for order in orders %}

                    <div class="product">
                        <div class="title">
                            ID: {{order.ref_code}}
                        </div>

                        <div class="text">
                            <div class="code">{{order.items.all.count}} Product(s)</div>
                            <div class="description">
                                {{order.ordered_date| date}}
                            </div>
                            <div class="review">
                                <span class="star-reviews">{{order.payment.get_method_display}}</span>
                            </div>
                            <div class="price">
                                {{order.get_total}}
                            </div>
                            <div class="shop-actions">
                                <a href="{{order.get_absolute_url}}">
                                    <button>Order detail</button></a>
                            </div>
                        </div>

                        <div class="preview">
                            <svg class="svg" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
                                <circle class="circle" cx="100" cy="100" r="100" />
                                <image class="image" xlink:href="{{order.items.all.first.item.cover.url}}" x="0" y="0" width="200px" height="180px" />
                            </svg>
                        </div>

                    </div>
                    {% empty %}
                    <div>

                        <div class="d-block " style="padding: 30px;">
                            <i class="fa fa-shopping-bag" aria-hidden="true"></i>
                            <h3>No Orders</h3>
                        </div>

                        <a href="/shop" class="btn">Continue shopping</a>
                    </div>

                    {% endfor %}



                </div>
            </div>
        </div>

        <div>
            {% include "snippets/only_album_snippet.html" %}

        </div>
    </div>
</div>
{% endblock content %}

templates/shop/payment-status.html
{% extends 'base.html' %}

{% block title %}
Order Status - Holykane - Solo Artist - Payment {{order.payment.get_status_display}}
{% endblock title %}


{% block content %}




<script>
    jQuery('#order_ag').on('click', () => {
        jQuery('body').load(`{% url "shop:checkout" %}`)
    })

    jQuery('#order_detail').on('click', () => {
        jQuery('body').load(`{% url "shop:order-detail" order.ref_code %}`)
    })

</script>
{% if order.payment.status == 's' %}

<div class="container">
    <!-- <div class="row"> -->
    <div class="text-center " style="text-align: center;padding: 20px; font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">
        <h1>
            Order Received

        </h1>
        <b> code #{{order.ref_code}}


        </b>
        <div class="circle  primary" style=" box-shadow: 2px 1px 1px 1px rgb(63, 33, 42);margin: 30px auto;text-align: center;font-size: 60px;height: 150px;width: 150px;padding: 30px ;border-radius:100px;background-color:rgb(38, 143, 69)">


            <i class="fa fa-thumbs-up" aria-hidden="true"></i>
            <!-- </div> -->
        </div> <small>Order Successful</small>
        <br>
        <button id="order_btn" data-url="{{order.get_absolute_url}}">View Order Detail</button>

    </div>
</div>
{% endif %}
{% if order.payment.status == 'p' %}

<div class="container">
    <!-- <div class="row"> -->
    <div class="text-center " style="text-align: center;padding: 20px; font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">
        <h1>
            Order completed </h1>

        <p>waiting confirmation..</p>


        <div class="circle  primary" style=" box-shadow: 2px 1px 1px 1px rgb(63, 33, 42);margin: 30px auto;text-align: center;font-size: 60px;height: 150px;width: 150px;padding: 30px ;border-radius:100px;background-color:rgb(145, 131, 131)">


            <i class="fa fa-smile-o" aria-hidden="true"></i> <!-- </div> -->
        </div> <small>Order pending</small> <br>
        <button id="order_btn" data-url="{{order.get_absolute_url}}">Order Detail</button>

    </div>
</div>

{% endif %}
{% if order.payment.status == 'f' %}

<div class="container">
    <!-- <div class="row"> -->
    <div class="text-center " style="text-align: center;padding: 20px; font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">
        <h1>
            Order Cannot be completed

        </h1>

        <div class="circle  primary" style=" box-shadow: 2px 1px 1px 1px rgb(63, 33, 42);margin: 30px auto;text-align: center;font-size: 60px;height: 150px;width: 150px;padding: 30px ;border-radius:100px;background-color:rgb(207, 23, 23)">


            <i class="fa fa-thumbs-down" aria-hidden="true"></i>
            <!-- </div> -->
        </div> <small>Order failed</small> <br>

        <button id="order_btn" data-url="/shop/checkout">Order Again</button>

    </div>
</div>
{% endif %}

{% include "snippets/latest_album_snippet.html" %}

<script>
    jQuery('#order_btn').on('click', (e) => {
        jQuery('body').load(jQuery('#order_btn').data('url'))
    })
</script>


{% endblock content %}

templates/shop/payment.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Complete Order - Holykane Solo Artist - Payment {{order.ref_code}}
{% endblock title %}


{% block content %}
<div class="container">
    <div class="text-center" style="text-align: center;">
        <form>
            <div> Proceed to Payment

                {{order.get_total}}
            </div>
            <button type="button" id="start-payment-button" class="btn-primary primary w-100" onclick="makePayment()">Pay Now</button>
        </form>
    </div>
</div>

<script src="https://checkout.flutterwave.com/v3.js"></script>
<br><br><br><br>
<script>
    function makePayment() {

        FlutterwaveCheckout({
            public_key: '{{flutter_key}}',
            tx_ref: '{{order.ref_code}}' + Math.floor(Math.random() * 99999 / 10),
            amount: '{{order.get_total.amount}}',
            currency: "{{order.get_total.currency}}",
            payment_options: "card, banktransfer, ussd",
            redirect_url: window.origin + `/shop/order/{{order.ref_code}}`,
            meta: {
                consumer_id: 23,
                consumer_mac: "92a3-912ba-1192a",
            },
            customer: {
                email: "{{order.billing_address.email}}",
                phone_number: "{{order.billing_address.phone}}",
                name: "{{order.billing_address.full_name}}",
            },
            customizations: {
                title: "The Holykane Solo Store",
                description: "Payment for {{order.ref_code}}",
                logo: window.origin + "{% static 'wp-content/uploads/sites/2/2014/09/logo_solo.png' %}",
            },
        });
    }
</script>
{% endblock content %}


{% block js %}

{% endblock js %}