blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import blogDetail, byCategory, add_comment, index

app_name = 'blog'
urlpatterns = [
    path('<date>/<slug>/', blogDetail, name='blog-detail'),
    path('category/<title>/', byCategory, name='by-category'),
    path('add-comment/<blog_id>',
         add_comment, name='add-comment'),
    path('', index, name='home'),
]

discography/urls.py
from django.contrib import admin
from django.urls import path, include

from discography.views import filter_products, remove_from_wish, remove_from_cart, discoMasonary, discoAll, songDetail, index, add_toFav, productDetail, shop, searched, add_to_cart, products_by_category, add_review_url, update_downloads, update_streams


app_name = 'discography'
urlpatterns = [
    path('shop/', shop, name='shop'),
    path('p/<pk>/<slug>', productDetail, name='product-detail'),
    path('album/<pk>/<slug>', songDetail, name='album-detail'),
    path('album/p/search/', searched, name='search'),
    path('album/p/add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('album/p/remove-from-cart/<slug>/',
         remove_from_cart, name='remove-from-cart'),
    path('album/p/add-review/<product_id>',
         add_review_url, name='add-review'),
    path('album/products-by-category/<category>/',
         products_by_category, name='products-by-category'),
    path('track/update-streams/<pk>/', update_streams, name='update-streams'),
    path('track/update-downloads/<pk>/',
         update_downloads, name='update-downloads'),
    path('track/favourite/<album_pk>/<song_pk>/',
         add_toFav, name='add-to-fav'),
    path('', index, name='home'),
    path('p/filter/', filter_products, name='product-filter'),
    path('masonry/', discoMasonary, name='masonry'),
    path('all', discoAll, name='all'),
    path('remove-from-wish/<type>/<pk>/',
         remove_from_wish, name='remove-from-wish'),

]

kaneweb/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('discography/', include('discography.urls', namespace='discography')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('artist-media/', include('media.urls', namespace='media')),
    path('events/', include('events.urls', namespace='events')), ]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, re_path
from .views import order, order_detail, payment_status, payment,  cart, checkout, wishlist

app_name = 'shop'

urlpatterns = [
    path('order/', order, name='order'),
    path('order-detail/<code>/', order_detail, name='order-detail'),
    path('order/<order_code>/',
         payment_status, name='payment-status'),
    path('cart/', cart, name='cart'),
    path('wishlist/', wishlist, name='wishlist'),
    path('checkout/', checkout, name='checkout'),
    path('payment/<type>/<order_id>/', payment, name='payment'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.text import slugify
from django.db.models.signals import post_save
# Create your models here.

STATUS = (
    (0, "Draft"),
    (1, "Published")
)


class Category(models.Model):  # Category for the Article
    title = models.CharField(max_length=200)  # Title of the Category
    created_on = models.DateTimeField(auto_now_add=True)  # Date of creation

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:by-category', kwargs={'title': self.title})


class BlogPost(models.Model):
    # Title of the Article
    title = models.CharField(max_length=200, unique=True)
    # Unique identifier for the article
    slug = models.SlugField(max_length=200, blank=True, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')  # Author of the Article
    # Short Description of the article
    description = models.CharField(max_length=500)
    # Content of the article, you need to install CKEditor
    content = RichTextUploadingField(config_name='awesome_ckeditor')
    tags = TaggableManager()  # Tags for a Particular Article, You need to install Taggit
    category = models.ForeignKey(
        'Category', related_name='category', on_delete=models.CASCADE)  # Category of the article
    keywords = models.CharField(max_length=250)  # Keywords to be used in SEO
    # Cover Image of the article
    cover = models.ImageField(upload_to='images/')
    created_on = models.DateTimeField(auto_now_add=True)  # Date of creation
    updated_on = models.DateTimeField(auto_now=True)  # Date of updation
    # Status of the Article either Draft or Published
    status = models.IntegerField(choices=STATUS, default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:blog-detail", kwargs={'slug': self.slug, 'date': str(self.created_on.date())})

    def get_add_comment_url(self):
        return reverse('blog:add-comment', kwargs={'blog_id': self.id})


class Comment(models.Model):
    user = models.ForeignKey(
        User,  on_delete=models.CASCADE,  related_name='blog_comments')
    comment = models.TextField(max_length=5000)
    post = models.ForeignKey(
        BlogPost, on_delete=models.CASCADE, null=True, related_name='comments')
    replies = models.ManyToManyField(
        'Comment', related_name='parent_comment', blank=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    website = models.URLField(blank=True, null=True)

    created_on = models.DateTimeField(auto_now_add=True)  # Date of creation
    updated_on = models.DateTimeField(auto_now=True)  # Date of updation

    def get_reply_url(self):
        return reverse('blog:reply-comment', kwargs={'pk': self.pk})

    def get_delete_comment_url(self):
        return reverse('blog:delete-comment', kwargs={'pk': self.pk})


def gen_slug(sender, created, instance: BlogPost, *args, **kwargs):
    if created:
        slug = slugify(instance.title)
        instance.slug = slug
        instance.save()


post_save.connect(gen_slug, sender=BlogPost)

shop/forms.py
from django import forms
from .models import Address
from django_countries.widgets import CountrySelectWidget


class BillingAddressesForm (forms.ModelForm):
    field_order = ['email', 'full_name',
                   'country', 'state', 'city', 'apartment_address', 'zip', 'default', ]
    address_type = forms.CharField(
        widget=forms.HiddenInput(attrs={'id': 'adr_type', 'hidden': 'true', 'value': 'B'}))

    class Meta:
        exclude = ['user', 'sessionID']
        model = Address


class ShippingAddressesForm (forms.ModelForm):
    field_order = ['email', 'full_name',
                   'country', 'state', 'city', 'apartment_address', 'zip', 'default', ]
    address_type = forms.CharField(

        widget=forms.HiddenInput(attrs={'id': 'adr_type', 'hidden': 'true', 'value': 'S'}))

    class Meta:
        exclude = ['user', 'sessionID']
        model = Address

discography/views.py
import uuid
from django.shortcuts import get_object_or_404, redirect, render
from django.db.models import Q, Count, Sum
from .models import Song
from shop.models import Review, Cart, Album
from django.core import paginator
from django.contrib import messages
from shop.views import shop
from shop.models import Album, ALBUM_CATEGORIES
import uuid
from django.shortcuts import get_object_or_404, redirect, render
from django.db.models import Q, Count, Sum
from .models import Song
from shop.models import Review, Cart, Album
from django.core import paginator
from django.contrib import messages
# Create your views here.
from core.views import get_session_id


def shop(request):
    eShop = Album.objects.all().order_by('-created_on')
    otherP = Album.objects.all().order_by('?')[:3]

    if str(request.GET.get('clr')) == 'True':
        request.session.__setitem__('orderby', 'default')
        request.session.__setitem__('min_price', 0)
        request.session.__setitem__('max_price', 100)

        return filter_products(request)

    paginated_qs = paginator.Paginator(eShop, 10)
    page_object_list = paginated_qs.page(1)
    page = request.GET.get('paged') if request.GET.get('paged') else 1
    if page:
        try:
            page_object_list = paginated_qs.page(page)
        except paginator.EmptyPage:
            page_object_list = paginated_qs.page(1)
        except paginator.PageNotAnInteger:
            page_object_list = paginated_qs.page(1)

    context = {

        'products': page_object_list,
        'page': page,
        'paginator': paginated_qs,
        'otherProducts': otherP,
        'orderby': 'default' if not request.session.get('orderby') else request.session.get('orderby'),
        'min_price': 0 if not request.session.get('min_price') else request.session.get('min_price'),
        'max_price': 100 if not request.session.get('max_price') else request.session.get('max_price')
        # 'max_price': '100'

    }
    if str(request.GET.get('flt')) == 'True':
        return filter_products(request)

    return render(request, 'discography/shop.html', context=context)


def filter_products(request):
    eShop = Album.objects.all().order_by('-created_on')
    otherP = Album.objects.all().order_by('?')[:3]
    orderBy = 'default' if not request.GET.get(
        'orderby') else request.GET.get('orderby')
    min_price = 0 if not request.GET.get(
        'min_price') else request.GET.get('min_price')
    max_price = 100 if not request.GET.get(
        'max_price') else request.GET.get('max_price')
    # print(min_price, max_price)

    if orderBy != 'default':

        request.session.__setitem__('orderby', orderBy)

    if max_price != 100:
        request.session.__setitem__('max_price', max_price)
    if min_price != 0:
        request.session.__setitem__('min_price', min_price)
    eShop = eShop.filter(price__gte=min_price,
                         price__lte=max_price)
    # print(min_price, max_price)
    if request.session.get('orderby') != 'default' and orderBy == 'default':
        orderBy = request.session.get('orderby')
    if request.session.get('min_price') != 0 and min_price == 0:
        min_price = request.session.get('min_price')

    if request.session.get('max_price') != 100 and max_price == 100:
        max_price = request.session.get('max_price')

    if orderBy == 'popularity':
        eShop = eShop.annotate(total_streams=Count(
            'songs__streams')).order_by('-total_streams')
    if orderBy == 'date':
        eShop = eShop.order_by('-created_on')
    if orderBy == 'rating':
        eShop = eShop.annotate(
            total_rating=Sum('reviews__rating')).order_by('-total_rating')
    if orderBy == 'price-desc':
        eShop = eShop.order_by('-price')
    if orderBy == 'price':
        eShop = eShop.order_by('price')
    paginated_qs = paginator.Paginator(eShop, 10)
    page_object_list = paginated_qs.page(1)
    page = request.GET.get('paged')
    if page:
        try:
            page_object_list = paginated_qs.page(page)
        except paginator.EmptyPage:
            page_object_list = paginated_qs.page(1)
        except paginator.PageNotAnInteger:
            page_object_list = paginated_qs.page(1)
    context = {
        'products': page_object_list,
        'paginator': paginated_qs,
        'otherProducts': otherP,
        'orderby': orderBy,
        'min_price': min_price,
        'query': True,
        'max_price': max_price,
        'page': page,
        # 'max_price': '100'
    }

    return render(request, 'layouts/products_list.html', context=context)


def add_toFav(request, album_pk, song_pk):

    album = get_object_or_404(Album, pk=album_pk)
    sessionId = request.session.get('sessionID')
    if not sessionId:
        sessionId = uuid.uuid1().hex
        request.session.__setitem__('sessionID', sessionId)
    if request.user.is_authenticated:

        albumFav = album.faved.all().filter(
            user=request.user, album=album)
        if albumFav.exists():
            albumFav = albumFav[0]
            if song_pk == 'all':
                albumFav.songs.set([song.id for song in album.songs.all()])
            else:
                songCheck = albumFav.songs.filter(pk=song_pk)
                if songCheck.exists():
                    albumFav.songs.remove(songCheck[0])
                else:
                    if albumFav.songs.count() == 0 and song_pk == 'none':
                        albumFav.delete()
                    else:
                        albumFav.songs.add(Song.objects.get(pk=song_pk))
        else:
            albumFav = album.faved.create(
                user=request.user,  album=album, )
            if song_pk == 'all':
                albumFav.songs.set([song.id for song in album.songs.all()])
            else:
                albumFav.songs.add(Song.objects.get(pk=song_pk))
    else:

        albumFav = album.faved.all().filter(
            sessionID=sessionId, album=album)
        if albumFav.exists():
            albumFav = albumFav[0]
            if song_pk == 'all':
                albumFav.songs.set([song.id for song in album.songs.all()])
            else:
                songCheck = albumFav.songs.filter(pk=song_pk)
                if songCheck.exists():
                    albumFav.songs.remove(songCheck[0])
                else:
                    if albumFav.songs.count() == 0 and song_pk == 'none':

                        albumFav.delete()
                    else:
                        albumFav.songs.add(Song.objects.get(pk=song_pk))
        else:
            albumFav = album.faved.create(
                sessionID=sessionId,  album=album, )
            if song_pk == 'all':
                albumFav.songs.set([song.id for song in album.songs.all()])
            else:
                albumFav.songs.add(Song.objects.get(pk=song_pk))

    return redirect(album.get_absolute_url())


def update_streams(request, pk):
    song = get_object_or_404(Song, pk=pk)

    sessionId = request.session.get('sessionID')
    if not sessionId:
        sessionId = uuid.uuid1().hex
        request.session.__setitem__('sessionID', sessionId)

    songStream = song.streams.get_or_create(
        user=request.user, sessionID=sessionId, song=song)
    songStream[0].count += 1
    songStream[0].save()
    return redirect(song.audio.url)


def update_downloads(request, pk):
    song = get_object_or_404(Song, pk=pk)

    sessionId = request.session.get('sessionID')
    if not sessionId:
        sessionId = uuid.uuid1().hex
        request.session.__setitem__('sessionID', sessionId)

    songDownloads = song.downloads.get_or_create(
        user=request.user, sessionID=sessionId, song=song)
    songDownloads[0].count += 1
    songDownloads[0].save()
    return redirect(song.audio.url)


def songDetail(request, pk, slug):
    album = get_object_or_404(Album, pk=pk, slug=slug)
    context = {
        'related_songs': Album.objects.filter(genre__name__contains=album.genre.name),
        'album': album

    }

    return render(request, 'discography/song-detail.html', context)


def productDetail(request, pk, slug):
    product = get_object_or_404(Album, pk=pk, slug=slug)
    context = {
        'related_products': Album.objects.filter(genre__name__contains=product.genre.name),
        'products': Album.objects.all().order_by('?').exclude(id=product.id),
        'product': product

    }
    return render(request, 'discography/product-detail.html', context)


def searched(request):
    query = request.GET.get('q')

    eShop = Album.objects.all().filter(Q(title__contains=query) | Q(songs__title=query) | Q(
        keywords=query) | Q(songs__producers__name__contains=query))
    otherP = Album.objects.all().order_by('?')[:3]

    if str(request.GET.get('clr')) == 'True':
        request.session.__setitem__('orderby', 'default')
        request.session.__setitem__('min_price', 0)
        request.session.__setitem__('max_price', 100)

        return filter_products(request)

    paginated_qs = paginator.Paginator(eShop, 10)
    page_object_list = paginated_qs.page(1)
    page = request.GET.get('paged') if request.GET.get('paged') else 1
    if page:
        try:
            page_object_list = paginated_qs.page(page)
        except paginator.EmptyPage:
            page_object_list = paginated_qs.page(1)
        except paginator.PageNotAnInteger:
            page_object_list = paginated_qs.page(1)

    context = {
        'query': query,
        'products': page_object_list,
        'page': page,
        'paginator': paginated_qs,
        'otherProducts': otherP,
        'orderby': 'default' if not request.session.get('orderby') else request.session.get('orderby'),
        'min_price': 0 if not request.session.get('min_price') else request.session.get('min_price'),
        'max_price': 100 if not request.session.get('max_price') else request.session.get('max_price')
        # 'max_price': '100'

    }

    if str(request.GET.get('flt')) == 'True':

templates/discography/disco-all.html
{% extends 'base.html' %}
{% block title %}
Discography -all|| Holykane Songs || Holykane
{% endblock title %}

{% block content %}
<main id="main">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="section-title">Discography</h3>
                <div class="row item-list ">
                    {% for album in albums %}

                    <div class="col-xs-12 col-sm-6 col-md-4 ">
                        <div class="item post-96 cpt_discography type-cpt_discography status-publish has-post-thumbnail hentry section-singles"> <a href="{{album.get_absolute_url}}" class="item-hold">
                                <figure class="item-thumb"> <img width="750" height="750" src="{{album.cover.url}}" class="attachment-ci_square size-ci_square wp-post-image" alt="" loading="lazy" srcset="{{album.cover.url}} 750w, {{album.cover.url}} 300w,
                                {{album.cover.url}} 150w, {{album.cover.url}} 100w, {{album.cover.url}} 110w, {{album.cover.url}} 560w" sizes="(max-width: 750px) 100vw, 750px" /></figure>
                            </a>
                            <div class="item-info">
                                <p class="item-title-main">{{album.title}}</p>
                                <p class="item-byline">{{album.record_label}}</p>
                            </div><a class="btn item-btn" href="{{album.get_absolute_url}}">Read More »</a>
                        </div>
                    </div>
                    {% empty %}
                    <center>
                        Nothing to show

                    </center>

                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

templates/discography/disco-masonary.html
{% extends 'base.html' %}
{% block title %}
Discography Masonry|| Holykane Songs || Holykane
{% endblock title %}

{% block content %}
<main id="main">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="section-title">Discography &#8211; Masonry</h3>
                <ul class="filters-nav group">
                    <li><a href="#filter" class="selected btn small transparent" data-filter="*">All Items</a></li>
                    {% for key,category in album_categories %}

                    <li><a href="#filter" class="btn small transparent" data-filter=".{{category}}">{{category}}</a></li>
                    {% endfor %}
                </ul>
                <div class="row item-list list-masonry">
                    {% for album in albums %}

                    <div class="col-xs-12 col-sm-6 col-md-4 {{album.get_category_display}}">
                        <div class="item post-96 cpt_discography type-cpt_discography status-publish has-post-thumbnail hentry section-singles"> <a href="{{album.get_absolute_url}}" class="item-hold">
                                <figure class="item-thumb"> <img width="750" height="750" src="{{album.cover.url}}" class="attachment-ci_masonry size-ci_masonry wp-post-image" alt="" loading="lazy" srcset="
                                {{album.cover.url}} 750w, {{album.cover.url}} 300w, 
                                {{album.cover.url}} 150w, {{album.cover.url}} 100w, {{album.cover.url}}
                                110w, {{album.cover.url}} 560w" sizes="(max-width: 750px) 100vw, 750px" /></figure>
                            </a>
                            <div class="item-info">
                                <p class="item-title-main">{{album.title}}</p>
                                <p class="item-byline">{{album.record_label}}</p>
                            </div><a class="btn item-btn" href="{{album.get_absolute_url}}">Read More »</a>
                        </div>
                    </div>
                    {% empty %}
                    <center>
                        Nothing to show

                    </center>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}

templates/discography/index.html
{% extends "base.html" %}

templates/discography/searches.html
{% extends 'base.html' %}


{% block title %}
Search Result for * {{query}} * | Holykane Solo

{% endblock title %}

{% block content %}
{% include "layouts/products_list.html" %}
{% endblock content %}

templates/discography/shop.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Holykane | Shop Products
{% endblock title %}


{% block content %}
{% include "layouts/products_list.html" %}
{% endblock content %}

templates/discography/song-detail.html
{% extends 'base.html' %}
{% block title %}
Album details | {{album.title}}| Holykane solo
{% endblock title %}


{% block content %}


<main id="main">
    <div class="container">
        <article id="entry-73" class="entry post-73 cpt_discography type-cpt_discography status-publish has-post-thumbnail hentry section-albums">
            <div class="row">
                <div class="col-xs-12">
                    <h1 class="section-title">{{album.title}}</h1>
                </div>
                <div class="col-md-4 col-sm-5 col-xs-12 col-md-push-8 col-sm-push-7">
                    <div class="sidebar">
                        <div class="item"><a data-rel="prettyPhoto" class="zoom" href="{{album.cover.url}}">
                                <figure class="item-thumb"> <img width="750" height="750" src="{{album.cover.url}}" class="attachment-ci_masonry size-ci_masonry wp-post-image" alt="" loading="lazy" srcset="
                                {{album.cover.url}} 750w, {{album.cover.url}} 300w, {{album.cover.url}} 150w, {{album.cover.url}} 100w, {{album.cover.url}} 110w, {{album.cover.url}} 560w" sizes="(max-width: 750px) 100vw, 750px" /></figure>
                            </a>
                            <table class="item-meta">
                                <tbody>
                                    <tr>
                                        <th>Release Date</th>
                                        <td>{{album.release_date | date}}</td>
                                    </tr>
                                    <tr>
                                        <th>Record Label</th>
                                        <td>{{album.record_label}}</td>
                                    </tr>
                                    <tr>
                                        <th>Catalog Number</th>
                                        <td>{{album.catalog_number}}</td>
                                    </tr>
                                    <tr>
                                        <th>AVAILABLE NOW AT</th>
                                        <td><a href="{{album.shop_link}}">{{album.shop_link}}</a></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-md-8 col-sm-7 col-xs-12 col-md-pull-4 col-sm-pull-5">
                    <div class="entry-content">
                        <ul class="tracklisting">
                            {% for song in album.songs.all %}

                            {% include "snippets/track.html" with detail=True album=album %}
                            {% endfor %}

                        </ul>
                        {{album.description | safe}}
                    </div>
                </div>
            </div>
        </article>
    </div>
</main>
{% endblock content %}